on: workflow_dispatch

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - run: echoooooo

  test-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-1"

  test-2:
    runs-on: ubuntu-latest
    if: always()
    needs: [test-1]
    steps:
      - run: echo ">>> test-2"

  test-3:
    runs-on: ubuntu-latest
    if: always()
    needs: [test-2]
    steps:
      - run: echo ">>> test-3"
