name: 2 Prep Failure
on: workflow_dispatch

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - run: echooooo

  test-1:
    needs: [prep]
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-1"

  test-2:
    needs: [test-1]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-2"

  test-3:
    needs: [test-2]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-3"
