name: 1 Success
on: workflow_dispatch

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - run: echo ">>> prep"

  test-1:
    needs: [prep]
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-1"
      - run: echo ${{ needs.prep.outputs.status }}

  # test-2:
  #   needs: [test-1]
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ">>> test-2"

  # test-3:
  #   needs: [test-2]
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ">>> test-3"
