name: 3 Test Failure
on: workflow_dispatch

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - run: echo ">>> prep"

  test-1:
    needs: [prep]
    if: needs.prep.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-1"

  test-2:
    needs:
      - prep
      - test-1
    if: needs.prep.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echooooooooo
  
  test-3:
    needs:
      - prep
      - test-2
    if: needs.prep.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> test-3"
